ikon-integration/ikui

package-lock.json
package.json
src/components/MultiSelect.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-2722

fix: multiselect labels

---

package.json
src/components/Button.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-2736

Feat: button default state

---

package-lock.json
package.json
src/components/Table.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-2761

fix: adjust table row size and text position

---

package-lock.json
package.json
src/components/Form/FormGroup.tsx
src/lib/utils.ts

https://ikonintegration.atlassian.net/browse/BCCSA-2714

fix: form group

---

package-lock.json
package.json
src/components/Tooltip.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-2720

feat: reduce default delay time for tooltip

---

package-lock.json
package.json
src/components/DateRangePicker.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-2659

fix: date range picker

---

package-lock.json
package.json
src/components/DataTable/index.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-2785

feat: add new version to data table

---

package-lock.json
package.json
src/components/DataTable/index.tsx
src/stories/components/DataTable/DataTable.stories.tsx

https://ikonintegration.atlassian.net/browse/CRES-46

feat: add initial sort state

---

package.json
src/components/Upload.tsx

https://ikonintegration.atlassian.net/browse/CRES-72

fix: upload enabled with actions disabled

---

package-lock.json
package.json
src/components/Drawer.tsx
src/stories/components/Drawer.stories.tsx

https://ikonintegration.atlassian.net/browse/DEVM-122

feat: add version to new drawer position

---

package-lock.json
package.json
src/components/InputCurrency.tsx
src/stories/components/InputCurrency.stories.tsx

https://ikonintegration.atlassian.net/browse/CRES-62

fix: input style

---

package.json
src/components/Upload.tsx

https://ikonintegration.atlassian.net/browse/CRES-84

fix: upload drag when disabled

---

package-lock.json
package.json
src/components/Upload.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3024

feat: change onPreview and onDownload to optional

---

package-lock.json
package.json
src/components/DataTable/DataTableViewOptions.tsx
src/components/Table.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3124

feat: create new version of table with new hover color and new view options order

---

package-lock.json
package.json
src/components/MultiSelect.tsx
src/stories/components/MultiSelect.stories.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3126

feat: alphabetical sort multiselect

---

package-lock.json
package.json
src/components/DatePicker.tsx
src/components/DateRangePicker.tsx
src/components/Input.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3138
https://ikonintegration.atlassian.net/browse/BCCSA-3139

feat: add new versions for datepickers components

---

package-lock.json
package.json
src/components/MultiSelect.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3126

feat: multiselect chosen options sort

---

package-lock.json
package.json
src/components/DatePicker.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3205

feat: clean value in date picker

---

package-lock.json
package.json

https://ikonintegration.atlassian.net/browse/DEVM-211

feat: update vite

---

package-lock.json
package.json
src/components/Tooltip.tsx
src/components/TooltipPrimitive.tsx
src/stories/components/Tooltip.stories.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3372

feat: new version of tooltip

---

package-lock.json
package.json
src/components/MultiSelect.tsx
src/stories/components/MultiSelect.stories.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3385

feat: add new version to disable sort input inside multiselect

---

.github/workflows/publish.yml
package-lock.json
package.json

https://ikonintegration.atlassian.net/browse/DEVM-224

feat: bump uikit to node 22

---

package-lock.json
package.json
src/components/DataTable/index.tsx
src/components/Dropdown.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3418

fix: adjust onRowClick to ignore button click

---

package-lock.json
package.json
src/components/DataTable/DataTableColumnHeader.tsx

https://ikonintegration.atlassian.net/browse/BCCSA-3471

feat: left align data table header
